### ISSUE TITLE
Would it be better not to configure the root logger in this library?

### ISSUE THREAD

**Issue by haoyun** [typesense/typesense-python#16]
https://github.com/typesense/typesense-python/blob/8a07f5ba1fd286e2f109866109effc25f50acd36/typesense/__init__.py#L4

If I import this package, before my own `logging.basicConfig()`,

```python
import logging
import typesense

logging.basicConfig(...)
...
```

then my code has no effect, unless I put `logging.basicConfig(...)` before `import typesense`. I think it might be better that this library only configures its own logger.

https://docs.python.org/3/library/logging.html#logging.basicConfig
> logging.basicConfig(**kwargs)¶
> This function does nothing if the root logger already has handlers configured...

**Comment by gamgi** [comment]
I also ran into issues with logging due to this. The preferred way for a library is to define its own logger with the library name, and not touch the root logger. Here's an example how [FastAPI](https://github.com/tiangolo/fastapi/blob/22528373bba6a654323de416ad5c867cbadb81bb/fastapi/logger.py) does it.

**Comment by kishorenc** [comment]
Gotcha, happy to accept a PR for this if it's a simple change.

**Comment by kishorenc** [comment]
Fixed by https://github.com/typesense/typesense-python/pull/19
